name: Snake Animation Workflow

on:
  push:
    branches:
      - main

jobs:
  snake_animation_job:
    runs-on: ubuntu-latest

    steps:
    - name: Snake animation
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.gabrielmedrado }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
